import { promises as fs } from 'node:fs';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec=promisify(execFile), base=path.resolve('.'), bundle=path.join(base,'run.mjs');
const destination=path.join(base,'artifacts','demo-'+Date.now());
await fs.mkdir(path.join(destination,'src'),{recursive:true});
await exec('git',['init','-q','-b','main'],{cwd:destination,windowsHide:true});
await fs.writeFile(path.join(destination,'src','auth.ts'),'export function authenticateUser(userId: string) {\n  return { userId, expiresIn: 3600 };\n}\n');
await fs.writeFile(path.join(destination,'package.json'),JSON.stringify({name:'driftbrief-demo',private:true,scripts:{test:'node --test'}},null,2));
const events=[],started=Date.now(); let clock=0;
function record(text){clock=Math.max(clock+1.2,(Date.now()-started)/1000);events.push([+clock.toFixed(3),'o',text.replaceAll('\n','\r\n')+'\r\n']);console.log(text);}
async function run(...args){const {stdout}=await exec(process.execPath,[bundle,...args,'--root',destination],{windowsHide:true});return JSON.parse(stdout);}
record('$ node .driftbrief/run.mjs init --clients codex,claude,cursor');
const installed=await run('init','--clients','codex,claude,cursor');record(installed.message);
record('$ driftbrief context "authenticateUser test"');
const before=await run('context','authenticateUser test');
if(!before.evidence.length)throw new Error('Demo must retrieve real source evidence');
record(JSON.stringify({evidence:before.evidence.map(e=>({path:e.path,excerpt:e.excerpt})),bytes:before.footprint.bytes},null,2));
record('Refactor: src/auth.ts -> src/session.ts; test script changes.');
await fs.rename(path.join(destination,'src/auth.ts'),path.join(destination,'src/session.ts'));
await fs.writeFile(path.join(destination,'src/session.ts'),'export function authenticateSession(userId: string) {\n  return { userId, expiresIn: 900, renewable: true };\n}\n');
await fs.writeFile(path.join(destination,'package.json'),JSON.stringify({name:'driftbrief-demo',private:true,scripts:{test:'node --test tests/session.test.mjs'}},null,2));
record('$ driftbrief context "authenticateSession test"');
const after=await run('context','authenticateSession test');
if(!after.evidence.length || !after.invalidated.length)throw new Error('Demo must demonstrate actual source invalidation');
record(JSON.stringify({invalidated:after.invalidated,evidence:after.evidence.map(e=>({path:e.path,excerpt:e.excerpt})),bytes:after.footprint.bytes},null,2));
record('$ driftbrief inspect --html');
const inspected=await run('inspect','--html');record('Offline evidence report generated.');
record('$ driftbrief uninstall');
const removed=await run('uninstall');record(JSON.stringify({removed:removed.removed,preserved:removed.preserved},null,2));
record('No task-level token or billing savings claimed. These are measured evidence payloads.');
await fs.mkdir('docs/demo',{recursive:true});
await fs.writeFile('docs/demo/evidence.html',(await fs.readFile(inspected.report,'utf8')).replace(/^[\t ]+$/gm,''));
await fs.writeFile('docs/demo/before.json',JSON.stringify(before,null,2));
await fs.writeFile('docs/demo/after.json',JSON.stringify(after,null,2));
const header={version:2,width:100,height:30,timestamp:Math.floor(started/1000),title:'DriftBrief: source evidence expires after a refactor',env:{TERM:'xterm-256color',SHELL:'node'}};
await fs.writeFile('docs/demo/walkthrough.cast',[header,...events].map(e=>JSON.stringify(e)).join('\n')+'\n');
const encoded=JSON.stringify(events).replaceAll('<','\\u003c');
await fs.writeFile('docs/demo/walkthrough.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>DriftBrief · recorded walkthrough</title><style>body{max-width:1050px;margin:40px auto;padding:0 24px;background:#101512;color:#eef1e4;font:16px system-ui}h1{font-size:36px;letter-spacing:-1px}p{color:#a6b5a5}button,a{background:#daef8a;color:#101512;border:0;border-radius:7px;padding:12px 18px;font:inherit;text-decoration:none;cursor:pointer}pre{background:#090e0b;border:1px solid #303d33;padding:24px;border-radius:12px;white-space:pre-wrap;overflow-wrap:anywhere;min-height:450px;font:13px/1.6 monospace}.bar{display:flex;gap:12px;align-items:center}span{color:#a6b5a5;font-size:12px}</style><h1>See old evidence expire.</h1><p>A recording of real local CLI runs against the included demo fixture. No AI output or savings numbers are simulated.</p><div class="bar"><button id="play">Replay recording</button><a href="evidence.html">Inspect evidence</a><span id="progress"></span></div><pre id="terminal"></pre><script>const frames=${encoded};let timers=[];function replay(){timers.forEach(clearTimeout);timers=[];document.getElementById('terminal').textContent='';for(const f of frames){timers.push(setTimeout(()=>{document.getElementById('terminal').textContent+=f[2];document.getElementById('progress').textContent=f[0].toFixed(1)+' s';},f[0]*600))}}document.getElementById('play').onclick=replay;replay();</script></html>`);
await fs.writeFile('artifacts/demo-location.json',JSON.stringify({root:destination,report:path.resolve('docs/demo/evidence.html')},null,2));
console.log('Recorded walkthrough: docs/demo/walkthrough.html');
